SELECT COUNT(1) AS TOTAL_REGISTROS_VENTAS FROM Venta;
SELECT COUNT(1) AS TOTAL_REGISTROS_PRODUCTO FROM Producto;
SELECT COUNT(1) AS TOTAL_REGISTROS_CLIENTE FROM Cliente;
SELECT COUNT(1) AS TOTAL_REGISTROS_METODO_PAGO FROM MetodoPago;
SELECT COUNT(1) AS TOTAL_REGISTROS_DETALLE_VENTA FROM DetalleVenta;

SELECT * FROM Venta;
SELECT * FROM Producto;
SELECT * FROM Cliente;
SELECT * FROM MetodoPago;
SELECT* FROM DetalleVenta;